# Generated by Django 5.2.1 on 2025-05-18 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starGift', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstargift',
            options={'verbose_name_plural': 'Users StarGifts'},
        ),
        migrations.AlterField(
            model_name='stargift',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stargift',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userstargift',
            name='star_gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_by_users', to='starGift.stargift'),
        ),
        migrations.AlterField(
            model_name='userstargift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_star_gifts', to=settings.AUTH_USER_MODEL),
        ),
    ]
