# Generated by Django 5.2.1 on 2025-05-18 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starGift', '0002_alter_userstargift_options_alter_stargift_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stargift',
            options={'verbose_name_plural': 'StarGift'},
        ),
        migrations.RenameField(
            model_name='userstargift',
            old_name='timestamp',
            new_name='received_date',
        ),
    ]
