# Generated by Django 5.2.1 on 2025-05-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starGift', '0003_alter_stargift_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstargift',
            name='get_from_app',
            field=models.BooleanField(default=False),
        ),
    ]
