# Generated by Django 5.2.1 on 2025-05-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starGift', '0004_alter_userstargift_get_from_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='stargift',
            name='convert_stars',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
