# Generated by Django 5.2.1 on 2025-05-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starGift', '0005_stargift_convert_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stargift',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
