# Generated by Django 5.2.1 on 2025-05-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starGift', '0006_alter_stargift_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stargift',
            name='popularity_add',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
