# Generated by Django 5.2.1 on 2025-05-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starGift', '0007_alter_stargift_popularity_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='stargift',
            name='sold_out',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
