# Generated by Django 5.2.1 on 2025-05-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starGift', '0008_stargift_sold_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stargift',
            name='lottie_animation_json',
            field=models.JSONField(),
        ),
    ]
