# Generated by Django 5.2.1 on 2025-05-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starGift', '0011_alter_userstargift_star_gift_alter_userstargift_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stargift',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
