# Generated by Django 5.2.1 on 2025-05-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starGift', '0012_alter_stargift_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stargift',
            name='lottie_animation_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
