# Generated by Django 5.2.1 on 2025-05-18 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0003_usercard_user_sender_alter_usercard_user'),
        ('starGift', '0003_alter_stargift_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roulette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cards', models.ManyToManyField(blank=True, related_name='roulettes_contain', to='card.card')),
                ('gifts', models.ManyToManyField(blank=True, related_name='roulettes_contain', to='starGift.stargift')),
            ],
        ),
        migrations.CreateModel(
            name='RouletteSpin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.card')),
                ('gift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='starGift.stargift')),
                ('roulette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to='roulette.roulette')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roulette_spins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
