# Generated by Django 5.2.1 on 2025-05-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roulettespin',
            old_name='card',
            new_name='prize_card',
        ),
        migrations.RenameField(
            model_name='roulettespin',
            old_name='gift',
            new_name='prize_gift',
        ),
    ]
