# Generated by Django 5.2.1 on 2025-05-21 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('starGift', '0013_alter_stargift_lottie_animation_json'),
        ('starGiftUnique', '0017_alter_userstargiftunique_star_gift_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.TimeField(auto_now=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('star_gift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='starGift.stargift')),
                ('star_gift_unique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='starGiftUnique.stargiftunique')),
            ],
        ),
    ]
