# Generated by Django 5.2.1 on 2025-05-21 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftsLogs', '0001_initial'),
        ('starGift', '0013_alter_stargift_lottie_animation_json'),
        ('starGiftUnique', '0017_alter_userstargiftunique_star_gift_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftlog',
            name='user_star_gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='starGift.userstargift'),
        ),
        migrations.AddField(
            model_name='giftlog',
            name='user_star_gift_unique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='starGiftUnique.userstargiftunique'),
        ),
    ]
