# Generated by Django 5.2.1 on 2025-05-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exception',
            new_name='LoggedException',
        ),
    ]
