# Generated by Django 5.2.1 on 2025-05-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0003_loggedexception_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedexception',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
