# Generated by Django 5.2.1 on 2025-05-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exception', '0004_alter_loggedexception_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedexception',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
