# Generated by Django 5.2.1 on 2025-05-18 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referals',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
