# Generated by Django 5.2.1 on 2025-05-18 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_popularityrecalcqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_popularity',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
    ]
