# Generated by Django 5.2.1 on 2025-05-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('youtube', 'Youtube'), ('instagram', 'Instagram')], max_length=50),
        ),
    ]
