# Generated by Django 5.2.1 on 2025-05-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emoji', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.CharField(blank=True, max_length=1024)),
                ('emojis', models.ManyToManyField(related_name='messages', to='emoji.emoji')),
            ],
        ),
    ]
