# Generated by Django 5.2.1 on 2025-05-16 18:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lottie_animation_json', models.JSONField(blank=True, null=True)),
                ('lottie_animation_url', models.URLField(blank=True, null=True)),
                ('popularity_add', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('drop_chance', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001')), django.core.validators.MaxValueValidator(Decimal('100.000000'))])),
                ('levels', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gift.gift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users Gifts',
            },
        ),
    ]
