# Generated by Django 5.2.1 on 2025-05-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergift',
            name='get_from_app',
            field=models.BooleanField(default=True),
        ),
    ]
