<template>
  <div class="liderbord-top-container">
    <LiderbordUser 
      :UserName="'AlexBoom'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="121200"
      :Possition="230"
    />
    <LiderbordUser 
      :UserName="'MaxPower'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="98000"
      :Possition="232"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
    <LiderbordUser 
      :UserName="'SuperCat'"
      :PhotoUrl="userStore.dataUnsafe.user.photo_url"
      :Popularity="75000"
      :Possition="233"
    />
  </div>
</template>

<script setup>

const userStore = useUserStore()

</script>

<style>

</style>