# Generated by Django 5.2.1 on 2025-05-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('offset', models.IntegerField()),
                ('length', models.PositiveIntegerField()),
                ('animated', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='emojis/')),
                ('animation_json', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
