# Generated by Django 5.2.1 on 2025-05-18 18:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0002_alter_message_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StarGiftUnique',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('popularity_add', models.PositiveIntegerField()),
                ('average_price', models.PositiveIntegerField()),
                ('drop_chance', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000001')), django.core.validators.MaxValueValidator(Decimal('100.000000'))])),
                ('levels', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStarGiftUnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(max_length=100)),
                ('num', models.PositiveIntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('pattern', models.CharField(max_length=100)),
                ('backdrop', models.CharField(max_length=100)),
                ('received_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('get_from_app', models.BooleanField(default=False)),
                ('lottie_animation_json', models.JSONField(blank=True, null=True)),
                ('lottie_animation_url', models.URLField(blank=True, null=True)),
                ('sender_id', models.BigIntegerField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_gift_messages', to='message.message')),
                ('star_gift_unique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_by_users', to='starGiftUnique.stargiftunique')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_star_gifts_unique', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users StarGifts',
            },
        ),
    ]
