# Generated by Django 5.2.1 on 2025-05-18 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starGiftUnique', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stargiftunique',
            options={'verbose_name_plural': 'StarGiftUnique'},
        ),
        migrations.AlterModelOptions(
            name='userstargiftunique',
            options={'verbose_name_plural': 'Users StarGiftsUnique'},
        ),
    ]
