# Generated by Django 5.2.1 on 2025-05-19 22:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starGiftUnique', '0002_alter_stargiftunique_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstargiftunique',
            unique_together={('user', 'star_gift_unique')},
        ),
    ]
