# Generated by Django 5.2.1 on 2025-05-19 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_alter_message_user_from_alter_message_user_to'),
        ('starGiftUnique', '0003_alter_userstargiftunique_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstargiftunique',
            name='lottie_animation_json',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='userstargiftunique',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='star_gift_messages', to='message.message'),
        ),
        migrations.AlterField(
            model_name='userstargiftunique',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userstargiftunique',
            name='num',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userstargiftunique',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
