# Generated by Django 5.2.1 on 2025-05-19 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starGiftUnique', '0004_alter_userstargiftunique_lottie_animation_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstargiftunique',
            name='model',
        ),
        migrations.RemoveField(
            model_name='userstargiftunique',
            name='title',
        ),
    ]
