# Generated by Django 5.2.1 on 2025-05-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starGiftUnique', '0010_alter_userstargiftunique_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stargiftunique',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
