# Generated by Django 5.2.1 on 2025-05-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starGiftUnique', '0011_alter_stargiftunique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stargiftunique',
            name='average_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stargiftunique',
            name='popularity_add',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
