# Generated by Django 5.2.1 on 2025-05-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starGiftUnique', '0012_alter_stargiftunique_average_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstargiftunique',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
