# Generated by Django 5.2.1 on 2025-05-21 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starGiftUnique', '0016_alter_userstargiftunique_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstargiftunique',
            name='star_gift_unique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_star_gift_unique', to='starGiftUnique.stargiftunique'),
        ),
    ]
