# Generated by Django 5.2.1 on 2025-05-18 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_usercard_user_sender_alter_usercard_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('count', models.PositiveIntegerField()),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.card')),
            ],
        ),
    ]
